import type { Category, DocItem } from '../types/doc';

// Clean, flat Apple-style SVG Mockups (macOS & iOS aesthetic)
const REGISTER_MOCKUP_SVG = `data:image/svg+xml;utf8,${encodeURIComponent(`
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 380" width="100%" height="100%">
  <!-- Canvas -->
  <rect width="100%" height="100%" fill="#fbfbfd" />
  
  <!-- macOS Window Frame -->
  <rect x="160" y="24" width="440" height="332" rx="14" fill="#ffffff" stroke="#d2d2d7" stroke-width="1" />
  
  <!-- Window Titlebar with Traffic Lights -->
  <rect x="160" y="24" width="440" height="38" rx="14" fill="#f5f5f7" />
  <rect x="160" y="48" width="440" height="14" fill="#f5f5f7" />
  <line x1="160" y1="62" x2="600" y2="62" stroke="#e5e5ea" stroke-width="1" />
  <circle cx="182" cy="43" r="5" fill="#ff5f56" stroke="#e0443e" stroke-width="0.5" />
  <circle cx="198" cy="43" r="5" fill="#ffbd2e" stroke="#dea125" stroke-width="0.5" />
  <circle cx="214" cy="43" r="5" fill="#27c93f" stroke="#1aab29" stroke-width="0.5" />
  <text x="380" y="47" font-family="-apple-system, system-ui, sans-serif" font-size="11" font-weight="500" fill="#86868b" text-anchor="middle">Create Account</text>

  <!-- Content -->
  <text x="380" y="96" font-family="-apple-system, system-ui, sans-serif" font-weight="600" font-size="18" fill="#1d1d1f" text-anchor="middle">Get Started</text>
  <text x="380" y="114" font-family="-apple-system, system-ui, sans-serif" font-size="11" fill="#86868b" text-anchor="middle">Enter your credentials to create your organization profile</text>

  <!-- Full Name -->
  <text x="195" y="146" font-family="-apple-system, system-ui, sans-serif" font-size="11" font-weight="500" fill="#48484a">Full Name</text>
  <rect x="195" y="153" width="370" height="32" rx="7" fill="#ffffff" stroke="#d2d2d7" stroke-width="1" />
  <text x="207" y="174" font-family="-apple-system, system-ui, sans-serif" font-size="12" fill="#1d1d1f">Alex Rivers</text>

  <!-- Email Address -->
  <text x="195" y="202" font-family="-apple-system, system-ui, sans-serif" font-size="11" font-weight="500" fill="#48484a">Email</text>
  <rect x="195" y="209" width="370" height="32" rx="7" fill="#ffffff" stroke="#d2d2d7" stroke-width="1" />
  <text x="207" y="230" font-family="-apple-system, system-ui, sans-serif" font-size="12" fill="#1d1d1f">alex.rivers@company.com</text>

  <!-- Password -->
  <text x="195" y="258" font-family="-apple-system, system-ui, sans-serif" font-size="11" font-weight="500" fill="#48484a">Password</text>
  <rect x="195" y="265" width="370" height="32" rx="7" fill="#ffffff" stroke="#0071e3" stroke-width="1.5" />
  <text x="207" y="286" font-family="-apple-system, system-ui, sans-serif" font-size="13" fill="#86868b">•••••••••••••</text>

  <!-- Apple Flat Primary Button -->
  <rect x="195" y="310" width="370" height="32" rx="7" fill="#0071e3" />
  <text x="380" y="330" font-family="-apple-system, system-ui, sans-serif" font-weight="500" font-size="12" fill="#ffffff" text-anchor="middle">Continue</text>
</svg>
`)}`;

const LOGIN_2FA_MOCKUP_SVG = `data:image/svg+xml;utf8,${encodeURIComponent(`
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 380" width="100%" height="100%">
  <!-- Canvas -->
  <rect width="100%" height="100%" fill="#fbfbfd" />
  
  <!-- macOS Modal Frame -->
  <rect x="180" y="28" width="400" height="324" rx="14" fill="#ffffff" stroke="#d2d2d7" stroke-width="1" />
  
  <!-- Titlebar -->
  <rect x="180" y="28" width="400" height="38" rx="14" fill="#f5f5f7" />
  <rect x="180" y="52" width="400" height="14" fill="#f5f5f7" />
  <line x1="180" y1="66" x2="580" y2="66" stroke="#e5e5ea" stroke-width="1" />
  <circle cx="202" cy="47" r="5" fill="#ff5f56" stroke="#e0443e" stroke-width="0.5" />
  <circle cx="218" cy="47" r="5" fill="#ffbd2e" stroke="#dea125" stroke-width="0.5" />
  <circle cx="234" cy="47" r="5" fill="#27c93f" stroke="#1aab29" stroke-width="0.5" />

  <!-- Shield Icon -->
  <circle cx="380" cy="106" r="22" fill="#f5f5f7" />
  <path d="M380 92 L392 98 V107 C392 115 387 121 380 124 C373 121 368 115 368 107 V98 Z" fill="#0071e3" />

  <text x="380" y="150" font-family="-apple-system, system-ui, sans-serif" font-weight="600" font-size="17" fill="#1d1d1f" text-anchor="middle">Two-Factor Authentication</text>
  <text x="380" y="170" font-family="-apple-system, system-ui, sans-serif" font-size="11" fill="#86868b" text-anchor="middle">Enter the 6-digit code generated by your authenticator app</text>

  <!-- Flat Digit Cells -->
  <rect x="235" y="194" width="42" height="46" rx="8" fill="#f5f5f7" stroke="#0071e3" stroke-width="1.5" />
  <text x="256" y="223" font-family="-apple-system, system-ui, sans-serif" font-size="20" font-weight="600" fill="#1d1d1f" text-anchor="middle">5</text>

  <rect x="284" y="194" width="42" height="46" rx="8" fill="#f5f5f7" stroke="#0071e3" stroke-width="1.5" />
  <text x="305" y="223" font-family="-apple-system, system-ui, sans-serif" font-size="20" font-weight="600" fill="#1d1d1f" text-anchor="middle">8</text>

  <rect x="333" y="194" width="42" height="46" rx="8" fill="#f5f5f7" stroke="#0071e3" stroke-width="1.5" />
  <text x="354" y="223" font-family="-apple-system, system-ui, sans-serif" font-size="20" font-weight="600" fill="#1d1d1f" text-anchor="middle">2</text>

  <rect x="385" y="194" width="42" height="46" rx="8" fill="#f5f5f7" stroke="#d2d2d7" stroke-width="1" />
  <text x="406" y="223" font-family="-apple-system, system-ui, sans-serif" font-size="20" font-weight="600" fill="#1d1d1f" text-anchor="middle">0</text>

  <rect x="434" y="194" width="42" height="46" rx="8" fill="#f5f5f7" stroke="#d2d2d7" stroke-width="1" />
  <text x="455" y="223" font-family="-apple-system, system-ui, sans-serif" font-size="20" font-weight="600" fill="#1d1d1f" text-anchor="middle">9</text>

  <rect x="483" y="194" width="42" height="46" rx="8" fill="#f5f5f7" stroke="#d2d2d7" stroke-width="1" />
  <text x="504" y="223" font-family="-apple-system, system-ui, sans-serif" font-size="20" font-weight="600" fill="#1d1d1f" text-anchor="middle">4</text>

  <!-- Button -->
  <rect x="235" y="260" width="290" height="34" rx="7" fill="#0071e3" />
  <text x="380" y="281" font-family="-apple-system, system-ui, sans-serif" font-weight="500" font-size="12" fill="#ffffff" text-anchor="middle">Verify & Authenticate</text>

  <text x="380" y="318" font-family="-apple-system, system-ui, sans-serif" font-size="11" font-weight="400" fill="#0071e3" text-anchor="middle">Use backup recovery code</text>
</svg>
`)}`;

const COURSE_CREATION_MOCKUP_SVG = `data:image/svg+xml;utf8,${encodeURIComponent(`
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 380" width="100%" height="100%">
  <!-- Canvas -->
  <rect width="100%" height="100%" fill="#fbfbfd" />
  
  <!-- macOS Window Frame -->
  <rect x="100" y="24" width="560" height="332" rx="14" fill="#ffffff" stroke="#d2d2d7" stroke-width="1" />
  
  <!-- Titlebar -->
  <rect x="100" y="24" width="560" height="38" rx="14" fill="#f5f5f7" />
  <rect x="100" y="48" width="560" height="14" fill="#f5f5f7" />
  <line x1="100" y1="62" x2="660" y2="62" stroke="#e5e5ea" stroke-width="1" />
  <circle cx="122" cy="43" r="5" fill="#ff5f56" stroke="#e0443e" stroke-width="0.5" />
  <circle cx="138" cy="43" r="5" fill="#ffbd2e" stroke="#dea125" stroke-width="0.5" />
  <circle cx="154" cy="43" r="5" fill="#27c93f" stroke="#1aab29" stroke-width="0.5" />
  <text x="380" y="47" font-family="-apple-system, system-ui, sans-serif" font-size="11" font-weight="500" fill="#86868b" text-anchor="middle">Course Studio</text>
  <rect x="560" y="34" width="80" height="22" rx="6" fill="#0071e3" />
  <text x="600" y="49" font-family="-apple-system, system-ui, sans-serif" font-weight="500" font-size="10" fill="#ffffff" text-anchor="middle">Publish</text>

  <!-- Left Form -->
  <text x="130" y="96" font-family="-apple-system, system-ui, sans-serif" font-size="11" font-weight="500" fill="#48484a">Course Title</text>
  <rect x="130" y="103" width="280" height="30" rx="6" fill="#ffffff" stroke="#d2d2d7" stroke-width="1" />
  <text x="140" y="122" font-family="-apple-system, system-ui, sans-serif" font-size="11" fill="#1d1d1f">Product Design Fundamentals</text>

  <text x="130" y="152" font-family="-apple-system, system-ui, sans-serif" font-size="11" font-weight="500" fill="#48484a">Curriculum Modules</text>
  <rect x="130" y="160" width="280" height="26" rx="6" fill="#f5f5f7" stroke="#e5e5ea" stroke-width="1" />
  <text x="142" y="177" font-family="-apple-system, system-ui, sans-serif" font-size="10" font-weight="500" fill="#1d1d1f">01 • Design Principles & Systems (4 lessons)</text>
  <rect x="130" y="192" width="280" height="26" rx="6" fill="#f5f5f7" stroke="#e5e5ea" stroke-width="1" />
  <text x="142" y="209" font-family="-apple-system, system-ui, sans-serif" font-size="10" font-weight="500" fill="#1d1d1f">02 • Typography & Grid Structures (6 lessons)</text>
  <rect x="130" y="224" width="280" height="26" rx="6" fill="#f5f5f7" stroke="#e5e5ea" stroke-width="1" />
  <text x="142" y="241" font-family="-apple-system, system-ui, sans-serif" font-size="10" font-weight="500" fill="#1d1d1f">03 • Micro-interactions & Prototyping (3 lessons)</text>

  <rect x="130" y="260" width="110" height="26" rx="6" fill="#ffffff" stroke="#d2d2d7" stroke-width="1" />
  <text x="185" y="277" font-family="-apple-system, system-ui, sans-serif" font-size="10" font-weight="500" fill="#1d1d1f" text-anchor="middle">+ Add Module</text>

  <!-- Right: Cover Art Card -->
  <text x="440" y="96" font-family="-apple-system, system-ui, sans-serif" font-size="11" font-weight="500" fill="#48484a">Cover Artwork</text>
  <rect x="440" y="103" width="190" height="115" rx="8" fill="#1d1d1f" />
  <circle cx="535" cy="150" r="18" fill="#ffffff" fill-opacity="0.15" />
  <polygon points="531,142 543,150 531,158" fill="#ffffff" />
  <text x="535" y="185" font-family="-apple-system, system-ui, sans-serif" font-size="10" font-weight="400" fill="#86868b" text-anchor="middle">16:9 Aspect Ratio</text>

  <rect x="440" y="228" width="190" height="28" rx="6" fill="#f5f5f7" stroke="#d2d2d7" stroke-width="1" />
  <text x="535" y="246" font-family="-apple-system, system-ui, sans-serif" font-size="10" font-weight="500" fill="#1d1d1f" text-anchor="middle">Replace Image...</text>
</svg>
`)}`;

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat-getting-started',
    name: 'Getting Started',
    iconName: 'Compass',
    order: 1,
    description: 'Introduction to platform documentation and system architecture.',
  },
  {
    id: 'cat-authentication',
    name: 'Authentication',
    iconName: 'ShieldCheck',
    order: 2,
    description: 'User registration, login, two-factor authentication, and security.',
  },
  {
    id: 'cat-courses',
    name: 'Course Management',
    iconName: 'GraduationCap',
    order: 3,
    description: 'Creating, structuring, publishing courses and managing enrolled students.',
  },
  {
    id: 'cat-api',
    name: 'API & Integrations',
    iconName: 'Webhook',
    order: 4,
    description: 'API keys, webhook endpoints, and client-side integration guides.',
  },
];

export const DEFAULT_DOCS: DocItem[] = [
  {
    id: 'doc-welcome',
    slug: 'welcome-overview',
    title: 'Platform Documentation',
    category: 'Getting Started',
    order: 1,
    badge: 'Overview',
    badgeColor: 'slate',
    description: 'A clean, centralized reference for architecture, authentication, and content creation.',
    readTime: '3 min read',
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-09-28T08:00:00Z',
    author: 'Design & Engineering',
    content: `
      <h2>System Architecture</h2>
      <p>Welcome to our streamlined <strong>Documentation Management Platform</strong>. Built with a clean, flat aesthetic, this workspace provides an uncluttered reading and authoring experience for technical guides and operational documentation.</p>
      
      <div class="callout callout-info">
        <div class="callout-icon">ℹ️</div>
        <div class="callout-body">
          <strong>Instant Search Shortcut</strong>
          <p>Press <kbd>⌘K</kbd> (or <kbd>Ctrl+K</kbd>) anywhere on the platform to search across all guides, topics, and code snippets.</p>
        </div>
      </div>

      <h2>Design Principles</h2>
      <ul>
        <li><strong>Flat & Monochromatic Foundation:</strong> Neutral canvases, subtle hairline dividers, and high-legibility typography designed for prolonged reading comfort.</li>
        <li><strong>Integrated Editor:</strong> Seamlessly toggle between reading and editing with typographic controls, special symbols, callouts, and local image uploads.</li>
        <li><strong>Client-Side Storage:</strong> Zero database requirements. All content is saved locally with instant JSON export and import capabilities.</li>
      </ul>

      <h2>Getting Started Guides</h2>
      <div class="steps-container">
        <div class="step-card">
          <div class="step-number">1</div>
          <div class="step-content">
            <h4>Authentication</h4>
            <p>Learn how users register their account, verify identity, and secure logins with Two-Factor Authentication.</p>
          </div>
        </div>
        <div class="step-card">
          <div class="step-number">2</div>
          <div class="step-content">
            <h4>Course Management</h4>
            <p>Discover how instructors structure curriculum modules, upload lesson materials, and publish to students.</p>
          </div>
        </div>
        <div class="step-card">
          <div class="step-number">3</div>
          <div class="step-content">
            <h4>Content Customization</h4>
            <p>Switch to <strong>Editor</strong> mode in the top navigation to add new sections, customize styles, or insert screenshots.</p>
          </div>
        </div>
      </div>
    `,
  },
  {
    id: 'doc-register',
    slug: 'how-to-register',
    title: 'How to Register a New Account',
    category: 'Authentication',
    order: 1,
    badge: 'Account',
    badgeColor: 'blue',
    description: 'Onboarding walkthrough, credential requirements, and email verification.',
    readTime: '4 min read',
    createdAt: '2026-09-22T10:00:00Z',
    updatedAt: '2026-09-28T08:15:00Z',
    author: 'Identity Team',
    content: `
      <h2>Overview</h2>
      <p>All prospective users must complete registration before accessing organization courses and dashboards. This guide outlines requirements, validation rules, and the confirmation flow.</p>

      <div class="doc-image-container">
        <img src="${REGISTER_MOCKUP_SVG}" alt="Registration Interface Mockup" class="doc-image" />
        <p class="image-caption">Figure 1.1 — macOS modal for initial user registration.</p>
      </div>

      <h2>Registration Flow</h2>
      <div class="steps-container">
        <div class="step-card">
          <div class="step-number">1</div>
          <div class="step-content">
            <h4>Navigate to Portal</h4>
            <p>Visit the system homepage and click <strong>Get Started</strong> in the navigation header.</p>
          </div>
        </div>

        <div class="step-card">
          <div class="step-number">2</div>
          <div class="step-content">
            <h4>Provide Details</h4>
            <p>Input your full name, work email address, and a secure password.</p>
          </div>
        </div>

        <div class="step-card">
          <div class="step-number">3</div>
          <div class="step-content">
            <h4>Verify Email Address</h4>
            <p>Enter the 6-digit confirmation PIN sent to your inbox to activate your account.</p>
          </div>
        </div>
      </div>

      <div class="callout callout-tip">
        <div class="callout-icon">💡</div>
        <div class="callout-body">
          <strong>Password Guidelines</strong>
          <p>Passwords must be a minimum of 8 characters and contain at least one uppercase letter, one number, and one symbol.</p>
        </div>
      </div>

      <h2>Account Roles</h2>
      <p>New registrations receive the default <code>Member</code> role. Privileged roles such as <code>Instructor</code> or <code>Administrator</code> must be granted by organization owners.</p>
    `,
  },
  {
    id: 'doc-login',
    slug: 'how-to-login',
    title: 'How to Login with Two-Factor Auth (2FA)',
    category: 'Authentication',
    order: 2,
    badge: 'Security',
    badgeColor: 'purple',
    description: 'Authentication procedure using credentials, TOTP authenticator codes, and backup keys.',
    readTime: '4 min read',
    createdAt: '2026-09-22T11:00:00Z',
    updatedAt: '2026-09-28T08:20:00Z',
    author: 'Security Engineering',
    content: `
      <h2>Two-Factor Verification</h2>
      <p>All administrator and instructor accounts require time-based one-time password (TOTP) verification using standard authenticator apps (Apple Passwords, Google Authenticator, or 1Password).</p>

      <div class="doc-image-container">
        <img src="${LOGIN_2FA_MOCKUP_SVG}" alt="2FA Verification Screen" class="doc-image" />
        <p class="image-caption">Figure 2.1 — Clean two-factor verification prompt.</p>
      </div>

      <h2>Sign-In Procedure</h2>
      <div class="steps-container">
        <div class="step-card">
          <div class="step-number">1</div>
          <div class="step-content">
            <h4>Enter Email & Password</h4>
            <p>Provide your registered credentials on the sign-in screen and select <strong>Continue</strong>.</p>
          </div>
        </div>

        <div class="step-card">
          <div class="step-number">2</div>
          <div class="step-content">
            <h4>Retrieve Authenticator Code</h4>
            <p>Open your authenticator app and locate the rolling 6-digit passcode.</p>
          </div>
        </div>

        <div class="step-card">
          <div class="step-number">3</div>
          <div class="step-content">
            <h4>Submit & Authorize Session</h4>
            <p>Enter the digits to complete sign-in. You may optionally select <em>Trust this browser for 30 days</em>.</p>
          </div>
        </div>
      </div>

      <div class="callout callout-warning">
        <div class="callout-icon">⚠️</div>
        <div class="callout-body">
          <strong>Recovery Codes</strong>
          <p>Store your 8 emergency backup codes in a safe location. If you lose access to your authenticator device, an emergency code is required to recover access.</p>
        </div>
      </div>
    `,
  },
  {
    id: 'doc-create-course',
    slug: 'create-a-course',
    title: 'How to Create and Configure a Course',
    category: 'Course Management',
    order: 1,
    badge: 'Authoring',
    badgeColor: 'blue',
    description: 'Setting up course metadata, syllabus modules, thumbnails, and lesson media.',
    readTime: '5 min read',
    createdAt: '2026-09-24T14:00:00Z',
    updatedAt: '2026-09-28T08:25:00Z',
    author: 'Curriculum Team',
    content: `
      <h2>Course Studio Overview</h2>
      <p>Instructors use the <strong>Course Studio</strong> to author syllabi, upload course materials, and manage student enrollments.</p>

      <div class="doc-image-container">
        <img src="${COURSE_CREATION_MOCKUP_SVG}" alt="Course Creation Studio Mockup" class="doc-image" />
        <p class="image-caption">Figure 3.1 — Studio interface for drafting lessons and uploading thumbnails.</p>
      </div>

      <h2>Step 1: Course Details</h2>
      <p>Supply the core information for your course catalog entry:</p>
      <ul>
        <li><strong>Title:</strong> A clear, descriptive course name.</li>
        <li><strong>Category:</strong> Primary subject area (e.g. Design, Engineering, Business).</li>
        <li><strong>Difficulty:</strong> Beginner, Intermediate, or Advanced.</li>
        <li><strong>Cover Artwork:</strong> Clean 16:9 thumbnail image (1280x720 recommended).</li>
      </ul>

      <h2>Step 2: Structuring Modules</h2>
      <div class="steps-container">
        <div class="step-card">
          <div class="step-number">1</div>
          <div class="step-content">
            <h4>Add Module</h4>
            <p>Create thematic chapters (e.g. <em>"Module 1: Design Principles"</em>).</p>
          </div>
        </div>

        <div class="step-card">
          <div class="step-number">2</div>
          <div class="step-content">
            <h4>Attach Lessons</h4>
            <p>Add text guides, video tutorials, or downloadable resource files.</p>
          </div>
        </div>

        <div class="step-card">
          <div class="step-number">3</div>
          <div class="step-content">
            <h4>Preview as Student</h4>
            <p>Test the curriculum flow from a learner's perspective before publishing.</p>
          </div>
        </div>
      </div>
    `,
  },
  {
    id: 'doc-publish-manage',
    slug: 'publishing-and-enrolling-students',
    title: 'Publishing Courses & Managing Students',
    category: 'Course Management',
    order: 2,
    badge: 'Operations',
    badgeColor: 'slate',
    description: 'Course review checklist, visibility controls, and roster management.',
    readTime: '4 min read',
    createdAt: '2026-09-24T16:00:00Z',
    updatedAt: '2026-09-28T08:30:00Z',
    author: 'Platform Ops',
    content: `
      <h2>Pre-Publishing Review</h2>
      <p>Ensure all quality checks are completed before making a course visible:</p>
      <ul>
        <li>All module lessons contain valid text or media content.</li>
        <li>At least one lesson is designated as a free sample preview.</li>
        <li>Lesson assessment quizzes have correct answer keys validated.</li>
      </ul>

      <h2>Enrolling Learners</h2>
      <ol>
        <li>Navigate to <strong>Course Studio &rarr; Student Roster</strong>.</li>
        <li>Click <strong>Invite Students</strong>.</li>
        <li>Paste learner emails and confirm invitation dispatch.</li>
      </ol>
    `,
  },
  {
    id: 'doc-api-keys',
    slug: 'api-webhooks',
    title: 'API Keys and Webhooks',
    category: 'API & Integrations',
    order: 1,
    badge: 'Developer',
    badgeColor: 'slate',
    description: 'Integrate enrollments and sync learning metrics using REST endpoints.',
    readTime: '4 min read',
    createdAt: '2026-09-25T11:00:00Z',
    updatedAt: '2026-09-28T08:35:00Z',
    author: 'Developer Relations',
    content: `
      <h2>REST API Overview</h2>
      <p>Use bearer token authentication to query user progress and automate student enrollments.</p>

      <div class="code-block">
        <div class="code-header">
          <span>bash</span>
          <button class="copy-button">Copy</button>
        </div>
        <pre><code>curl -X POST https://api.yourdomain.com/v1/courses/design-fundamentals/enroll \\
  -H "Authorization: Bearer sec_live_0984712048" \\
  -H "Content-Type: application/json" \\
  -d '{
    "studentEmail": "alex.rivers@company.com",
    "sendWelcomeEmail": true
  }'</code></pre>
      </div>
    `,
  },
];
